version: '3.1'

services:

  mongo:
    image: midas_mongo:test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  backend:
    image: midas_backend:test
    restart: always
    ports:
      - 4000:4000
      - 3000:3000
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo