apiVersion: v1
kind: Secret
metadata:
  name: mongo
type: Opaque
stringData:
  mongo: mongodb://{{ .Values.mongodb.auth.rootUser }}:{{ .Values.mongodb.auth.rootPassword }}@{{ .Release.name }}-headless:27017/