apiVersion: v1
kind: Secret
metadata:
  name: mongo
type: Opaque
stringData:
  mongo: mongodb://{{index .Values "mongodb-sharded" "auth" "rootUser" 0 }}:{{index .Values "mongodb-sharded" "auth" "rootPassword" 1 }}@{{ .Release.Name . }}-mongos:{{ index .Values "mongodb-sharded" "service" "ports" "mongodb" }}