apiVersion: v1
kind: Secret
metadata:
  name: mongo
type: Opaque
stringData:
  mongo: mongodb://{{index .Values "mongodb-sharded" "auth" "rootUser" }}:{{index .Values "mongodb-sharded" "auth" "rootPassword" }}@{{ .Release.Name }}-mongodb-sharded:{{ index .Values "mongodb-sharded" "service" "ports" "mongodb" }}/?authSource=admin