apiVersion: v1
kind: Service
metadata:
  name: {{ include "midasbackend.fullname" . }}-api
spec:
  type: {{ .Values.services.api.type }}
  ports:
    - port: {{ .Values.services.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "midasbackend.selectorLabels" . | nindent 4 }}
