name: backend-action
run-name: Check backend PR basic stability
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]

jobs:
  build_test:
    if: github.head_ref == 'frontend' || github.head_ref == 'backend'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Enter backend directory
      run: cd backend
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm i
    - name: build
      run: npm run build
  
  ctr_build:
    needs: ["build_test"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Enter backend directory
      run: cd backend
    - name: Build the Docker image
      run: docker build . --tag midas_backend:test
    - name: Test the Docker image
      run: |
        docker run -d -p 4000:4000 midas_backend:test
        sleep 3
    - name: Get HTTP response from "localhost:4000"
      run: "curl -f localhost:4000"
    
  telegram_notify:
    needs: ["ctr_build"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message: ["Pending Midas repository pull request from ${{ github.event.pull_request.user.login }}"]
    steps:
      - name: Notify owner in Telegram
        run: 'curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_ID }} -d text="${{ matrix.message }}" > /dev/null'