name: backend-action
run-name: Check backend PR basic stability
on:
  pull_request:
    types: [opened, reopened]
    branches: ["main"]

jobs:
  ctr_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        username: ["test"]
        password: ["test"]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Build the mongodb Docker image
      run: docker build . --tag midas_mongo:test
      working-directory: ./mongo
    - name: Run mongodb
      run: |
        docker run -e MONGO_INITDB_ROOT_USERNAME="${{ matrix.username }}" -e MONGO_INITDB_ROOT_PASSWORD="${{ matrix.password }}" -d -p 27017:27017 --name mongo midas_mongo:test
        sleep 2
        echo $(docker exec mongo "ls /data/db/")
      working-directory: ./mongo

    - name: Build the Docker image
      run: docker build . --tag midas_backend:test
      working-directory: ./backend
    - name: Test the Docker image
      run: |
        docker run -e MONGO_URI="mongodb://${{ matrix.username }}:${{ matrix.password }}@localhost:27017/Avito" -d -p 4000:4000 --name backend midas_backend:test
        sleep 3
        echo $(docker ps)
        docker logs backend
      working-directory: ./backend
    - name: Get HTTP response from "localhost:4000/api/admin/"
      run: "curl -f localhost:4000/api/admin/"
    
  telegram_notify:
    needs: ["ctr_build"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message: ["Backend passed | Pending Midas repository pull request from ${{ github.event.pull_request.user.login }}"]
    steps:
      - name: Notify owner in Telegram
        run: 'curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_ID }} -d text="${{ matrix.message }}" > /dev/null'