name: backend-action
run-name: Check backend PR basic stability
on:
  pull_request:
    types: [opened, reopened]
    branches: ["main"]

jobs:
  ctr_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Build the mongodb Docker image
      run: docker build . --tag midas_mongo:test
      working-directory: ./mongo

    - name: Build the Docker image
      run: docker build . --tag midas_backend:test
      working-directory: ./backend

    - name: Test images via docker-compose
      run: |
        docker-compose up -d
        sleep 10
      working-directory: ./backend
    - name: Get HTTP response from "localhost:4000/api/admin/"
      run: "curl -f localhost:4000/api/admin/"
    
  telegram_notify:
    needs: ["ctr_build"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message: ["Backend passed | Pending Midas repository pull request from ${{ github.event.pull_request.user.login }}"]
    steps:
      - name: Notify owner in Telegram
        run: 'curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_ID }} -d text="${{ matrix.message }}" > /dev/null'