name: frontend-action
run-name: Check frontend PR basic stability
on:
  pull_request:
    types: [opened, reopened]
    branches: ["main"]

jobs:
  ctr_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Build the Docker image
      run: docker build . --tag midas:test
      working-directory: ./client
    - name: Test the Docker image
      run: |
        docker run -d -p 8080:8080 midas:test
        sleep 3
      working-directory: ./client
    - name: Get HTTP response from "localhost:8080"
      run: "curl -f localhost:8080"
    
  telegram_notify:
    needs: ["ctr_build"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message: ["Frontend passed | Pending Midas repository pull request from ${{ github.event.pull_request.user.login }}"]
    steps:
      - name: Notify owner in Telegram
        run: 'curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_ID }} -d text="${{ matrix.message }}" > /dev/null'