name: frontend-check
run-name: Check frontend PR basic stability
on:
  push: #delete this after tests
    branches: ["frontend"]
  pull_request:
    types: [opened, reopened]
    branches: ["main"]
jobs:
  test:
    if: contains(github.ref, 'frontend')
    runs-on: ubuntu-latest
    strategy:
      matrix:
<<<<<<< HEAD
        node-version: [16.2.0, 14, 16]
=======
        node-version: [16.x, 18.x]
>>>>>>> 7311579c740153b091a2d342c447ad8f58685634
    steps:
    - uses: actions/checkout@v4
      with:
        ref: frontend
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm i
    - name: install dependencies
      run: npm install @emotion/react @emotion/styled
    - run: npm run build --if-present
    - name: Test
      run: npm test